[package]
name = "brc"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = { version = "0.16.0", default-features = false, features = [
    "rayon",
    "inline-more",
    "default-hasher",
] }
rayon = { version = "1.11.0", default-features = false }
