[package]
name = "brc"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap2 = { version = "0.9.8", default-features = false }
dashmap = { version = "6.1.0", default-features = false, features = [
    "rayon",
    "inline",
] }
rayon = { version = "1.11.0", default-features = false }
